### ISSUE TITLE
Moving platforms with waypoint system

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-metroidvania-2d#18]
Implement flexible moving platforms, that cycle through waypoints, represented by Node2Ds (or Position2Ds, any type of Node2D should work).

- [x] Merge the waypoint platforms from the corresponding tutorial
- [ ] Replace the moving platforms implemented by @henriiquecampos with this unique system

**Comment by NathanLovato** [comment]
Started with ab710a1e7e6826aa5ca1f1ea97a9a667347ca7b6

**Comment by henriiquecampos** [comment]
I don't recall implementing moving platforms :thinking: 

Anyway, this is the system I am using in Kitchen Tales, instead of way points I am using a Path, a PathFollow and a RemoteTransform, with Animations and AnimationPlayer. No code required.

[moving-platform.zip](https://github.com/GDquest/godot-metroidvania-2d/files/3241090/moving-platform.zip)

**Comment by NathanLovato** [comment]
Done with ab710a1e7e6826aa5ca1f1ea97a9a667347ca7b6
