### ISSUE TITLE
Discussion: Readme and project outline

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-metroidvania-2d#2]
As I said we'd be open about our process, I put the project's outline in the repo's [README](https://github.com/GDquest/godot-metroidvania-2d/blob/master/README.org). This way anyone can read it and join this discussion.

This is a general outline that encompasses the entire project, defines its scope, and our general intention with the course. This is NOT a game concept or game design document.

I could use some feedback:

- Is anything unclear or hard to understand?
- Should we develop some sections?
- Any other questions and suggestions are welcome.

*Note: this task is to discuss the project. If you have other questions about other tutorials, our progress, etc. please ping me on Discord*

**Comment by henriiquecampos** [comment]
> focus more on design and less on code
> we will focus on game design, **implementing mechanics**, **programming patterns**…

I think a clarification on how these techniques, together with other design techniques, will be approached in order to favor `focus more on design and less on code` would be nice, so viewers can have a clearer knowledge on the kind of content that they will get and how will we package this content for them.

> Is anything unclear or hard to understand?

I think this part:
> Get people to work together and become contributors to open source project

In the [Open Source From Start](https://github.com/GDquest/godot-metroidvania-2d#open-source-from-the-start) section we claim learners, and correct me if I'm wrong, the community in general, will be able to contribute.

I think a brief explanation on this take to clarify when this will happen would be nice. The major questions I have in mind are: 
- Will the course and the demo be done in parallel or the demo first and then the course?
- In which case, when/where will contributors/learners take place?
- What kind of assignment/content can they expect to be accepted?

**Comment by NathanLovato** [comment]
> I think a clarification on how these techniques, together with other design techniques, will be approached in order to favor focus more on design and less on code would be nice

Sure, but we need more work on the project and feedback from the community first. I'm waiting for backers to fill the form I shared and mentioned yesterday.

Regarding contributions, these are good questions. We have to create the demo before the course as the course relies on the demo. At least, we have to write a fair part of it first.

We'll have to write some contribution guide as well.

**Comment by NathanLovato** [comment]
There's been no extra feedback here, so closing for now
