### ISSUE TITLE
Should we have a play method on Player to play animations?     This is a code structure question related to teaching/making tutorials.

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-metroidvania-2d#45]
As in OpenRPG, I've opted for a Skin node for the characters' skin, so we can replace the animated characters, so an animator or artist can work on animations without messing with the code/git history, and so we can mix-and-match animation techniques without other bits of code breaking.

This makes it so to start an animation from a state, we have to use player.skin.play(animation_name). So this makes the skin property a dependency for each state that accesses it. This is +/- fine as they're all part of the same scene. But I'd like your thoughts on using this kind of code vs adding public methods on Player.gd to encapsulate functionality. In the states, this would result in having

```
player.skin.play(animation_name)
```

vs

```
player.play(animation_name)
```

And adding an extra play method on Player:

```
func play(animation_name: String) -> void:
    skin.play(animation_name)
```

Which one should we teach or recommend? I'd use `player.skin.play()` as it makes it clear that you're giving work to the skin node. And I think that both approaches have downsides. I wouldn't want to clutter Player.gd, the Player node being a KinematicBody2D node.

*Yes, our lives as developers is complicated*

**Comment by NathanLovato** [comment]
Ping @razcore-art

**Comment by henriiquecampos** [comment]
I think it is better to use `Player.play()`. 
> encapsulate what changes

If we decide to change anything in the `Skin` or related to it, the interface provided to the states will stay the same and we would only have to change the content of the `Player.play()` method.

**Comment by razcore-art** [comment]
> As for cluttering the Player class, maybe it is better to decouple the two responsibilities, the change in state from the animation being played. This will also avoid this problem.
> 
> We can have the player sending signals about its current state and let the `Skin` decide what to do with this information.

Unfortunately it's not that simple since the player shouldn't do anything while the animation plays so it's not just a matter of letting `Skin` do it's own work. At this time I can't think of anything that would possibly decouple the `Skin` animation from the player state change.

As far as using `Player.play()` instead of `Player.skin.play()` or similar I'd opt for `Player.skin.play()` as it is indeed more clear about what's happening plus the other mentioned advantages - no cluttering of `Player` etc. We wouldn't run in the API/Interface issue since, if we do the stuff right, `play` would be a public method that shouldn't rely on the private implementation so it's just like `Player.play()` in this sense. We can still explain the API/Interface concept just as well, that's basically the public/pseudo-private methods/variables issue.

**Comment by NathanLovato** [comment]
> We can have the player sending signals about its current state and let the Skin decide what to do with this information.

Although that makes it so when the state machine changes state, you have to figure out where the code to change the animation is. I think it complicates the code.

> We wouldn't run in the API/Interface issue since, if we do the stuff right, play would be a public method that shouldn't rely on the private implementation

Makes sense, keeping it like that for now then
